controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

comercio_delete:
    path: '/comercio/{id}/delete'
    controller: App\Controller\AdminController::delete

categoria_delete:
    path: '/categoria/{id}/delete'
    controller: App\Controller\AdminController::deleteCategoria

usuario_delete:
    path: '/usuario/{id}/delete'
    controller: App\Controller\AdminController::deleteUsuario

foto_delete:
    path: '/foto/{id}/delete'
    controller: App\Controller\AdminController::deleteFoto

horario_delete:
    path: '/horario/{id}/delete'
    controller: App\Controller\AdminController::deleteHorario